### PR TITLE
add possibility to register namespaces to DOMXpath

### PR DESCRIPTION
**Pull request by troosan**

### CODE REVIEW

**Comment by Progi1984** [comment]
@troosan That lacks an unit test :)

**Comment by troosan** [comment]
The whole class is lacking unit tests ;-)

**Comment by Progi1984** [comment]
@troosan Yes... but we are in continuous improvment :)

**Comment by troosan** [comment]
@Progi1984 In the spirit of constant improvement, 100% code coverage for the XMLReader

**Comment by Progi1984** [comment]
@troosan Good job :)

**Comment by troosan** [comment]
@Progi1984 do you think we could release a 0.2.8?
This feature is needed in PhpWord to parse Drawings.
Thanks!

**Pull request merged**
